edition = "2018"
tab_spaces = 4
use_field_init_shorthand = true
use_try_shorthand = true
max_width = 100
use_small_heuristics = "Default"
fn_args_layout = "Tall"

unstable_features = true

blank_lines_upper_bound = 2
brace_style = "SameLineWhere"
condense_wildcard_suffixes = true
control_brace_style = "AlwaysSameLine"
format_strings = true
imports_layout = "HorizontalVertical"
match_arm_blocks = false
imports_granularity = "Crate"
overflow_delimited_expr = true
reorder_impl_items = true
space_after_colon = true
spaces_around_ranges = true
trailing_semicolon = true
where_single_line = true